name: CI/CD

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build

      - name: Run type check
        run: pnpm run typecheck

      - name: Run lint
        run: pnpm run lint

      #   - name: Run tests
      #     run: pnpm run test

      # - name: Create Deployment Status
      #   if: success()
      #   run: |
      #     gh api \
      #       --method POST \
      #       -H "Accept: application/vnd.github+json" \
      #       /repos/${{ github.repository }}/environments/production/protection_rules \
      #       -f required_contexts='["test"]' # Corrected context name to match job name
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: test # This ensures deploy only runs after tests pass
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Only deploy on main branch pushes

    steps:
      - name: Deploy to Vercel
        id: deploy
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
